# $FreeBSD$

freebsd_instance:
  image: freebsd-12-2-release-amd64
  cpu: 8
  memory: 8G

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  name: World and kernel amd64 build test
  timeout_in: 90m
  install_script:
  - pkg install -y qemu-devel uefi-edk2-qemu-x86_64
  script:
  - make -j$(sysctl -n hw.ncpu) WITHOUT_TOOLCHAIN=yes buildworld buildkernel
# FAT root fs fails on stable/12:
# Mounting from msdosfs:/dev/ada0s1 failed with error 19.
#
#  test_script:
#  - sh tools/boot/ci-qemu-test.sh
